### ISSUE TITLE
Bug in pnm2019/pnflow/src/pnm/pnflow/utility.cpp

### ISSUE THREAD

**Issue by sirazenok** [aliraeini/pnflow#1]
Lines 527-528 don't do what they are proposed for.  

Now it's  

 if((pOne->model()->clusterIndex() == 0 && pOne->model()->clusterIndex() == 0) ||    // None or both are marked ->
            (!pOne->model()->clusterIndex() == 0 && !pOne->model()->clusterIndex() == 0))   // assign on 50/50 basis  

and it works for every pOne and pTwo regardless of their values.  

It need's to be  

 if((pOne->model()->clusterIndex() == 0 && pTwo->model()->clusterIndex() == 0) ||    // None or both are marked ->
            (!pOne->model()->clusterIndex() == 0 && !pTwo->model()->clusterIndex() == 0))   // assign on 50/50 basis  

to work as proposed.

**Comment by aliraeini** [comment]
Thanks sirazenok for reporting this, I think I couldn't figure out what has been the intention of this part of the code and rewrite it myself, now this is handled in lines 100-125 of file [setGVoidProps.h](https://github.com/aliraeini/pnflow/blob/master/src/pnm/pnflow/polygon/setGVoidProps.h). 

FYI, The pnm2019 branch you are referring is just for backup and will eventually be deleted, only the default [master](https://github.com/aliraeini/pnflow/tree/master) branch will receive bug fix and occasional updates to keep it in sync with my local branches.   I guess this shows the importance of checking for updates when using a tool.
